### ISSUE TITLE
Build error when using css.

### ISSUE THREAD

**Issue by haydermabood** [glook/webpack4-react-boilerplate#16]
Hello, I am getting the following error when I try to add a css file to the vanilla project: 

`
ERROR in ../src/styles/styles.css (../node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].use[1]!../node_modules/resolve-url-loader/index.js??ruleSet[1].rules[5].use[2]!../node_modules/css-loader/dist/cjs.js!../src/styles/styles.css)
Module build failed (from ../node_modules/resolve-url-loader/index.js):
Error: resolve-url-loader: error processing CSS
  .../src/styles/styles.css:1:1: Unknown word
  at Input.error (.../sample-project/node_modules/resolve-url-loader/node_modules/postcss/lib/input.es6:108:16)
    at encodeError (.../sample-project/node_modules/resolve-url-loader/index.js:287:12)
    at onFailure (.../sample-project/node_modules/resolve-url-loader/index.js:228:14)
 @ ../src/styles/styles.css 8:20-236 61:4-82:5 64:18-234
 @ ../src/index.tsx 8:0-28
`

**Comment by DeDaawg65** [comment]
I too am getting this error when trying to bring in third party library i.e. react-toastify   (its not the only one just an example)

ERROR in ../node_modules/react-toastify/dist/ReactToastify.min.css (../node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].use[1]!../node_modules/resolve-url-loader/index.js??ruleSet[1].rules[5].use[2]!../node_modules/style-loader/dist/cjs.js!../node_modules/css-loader/dist/cjs.js!../node_modules/react-toastify/dist/ReactToastify.min.css)
Module build failed (from ../node_modules/resolve-url-loader/index.js):
Error: resolve-url-loader: error processing CSS
  file://C:\Projects\Dennis\APPLICATION.UI.REACT\node_modules\react-toastify\dist\ReactToastify.min.css:2:7: Unknown word
  at Input.error (C:\Projects\Dennis\APPLICATION.UI.REACT\node_modules\resolve-url-loader\node_modules\postcss\lib\input.es6:108:16)
    at encodeError (C:\Projects\Dennis\APPLICATION.UI.REACT\node_modules\resolve-url-loader\index.js:287:12)
    at onFailure (C:\Projects\Dennis\APPLICATION.UI.REACT\node_modules\resolve-url-loader\index.js:228:14)
 @ ../node_modules/react-toastify/dist/ReactToastify.min.css 8:20-239 61:4-82:5 64:18-237
 @ ../src/pages/App/App.tsx 4:0-51
 @ ../src/pages/index.tsx 3:0-26 3:0-26
 @ ../src/index.tsx 8:0-29 11:88-91

Any help would be greatly appreciated.

**Comment by glook** [comment]
@haydermabood @DeDaawg65 Hi, thank you for this issue request. It was fixed in 1.0.7

**Comment by DeDaawg65** [comment]
Thank you so much for the fix, awesome work!
