### ISSUE TITLE
Why is the devserverHost of non-windows is 0.0.0.0

### ISSUE THREAD

**Issue by Hujianboo** [glook/webpack4-react-boilerplate#17]
My development machine is a mac. When I started it, I found that the js file could not be found, and the js path address was found to be 0.0.0.0. The correct path is 127.0.0.1
`export const devServerHost = isWindows() ? '127.0.0.1' : '0.0.0.0';`

**Comment by glook** [comment]
Hi, you are using safari, right?

**Comment by Hujianboo** [comment]
> Hi, you are using safari, right?

chrome :-)

**Comment by Hujianboo** [comment]
> 
Excuse me, under what scenarios do I need a 0.0.0.0 address? I don't think this place is necessary to make such judgments, right? I don’t seem to have encountered this problem before, and I want to know the specific reason. thx

**Comment by glook** [comment]
Hi, i checked it again and got that you are right. I cant find any reason to use 0.0.0.0 as default host for any non windows machines. In 1.0.7 host property was removed from devServer config.
