### ISSUE TITLE
start script not working

### ISSUE THREAD

**Issue by flaviuse** [glook/webpack4-react-boilerplate#3]
Hello the project is currently not working:
Installation and build script are working as expected but 
- start script throws an error:
![Screenshot 2020-11-10 at 11 31 27](https://user-images.githubusercontent.com/40322270/98662584-4bb98900-2348-11eb-9d29-2a54ccd7627c.png)
It seems related to the web server

**Comment by glook** [comment]
Hello @flaviuse, thanks for your issue. I will release a new update soon.
